### ISSUE TITLE
provide parent pom.xml

### ISSUE THREAD

**Issue by umjammer** [lostromb/concentus#18]
i want to use [jitpack.io](https://jitpack.io/).
but jitpack.io doesn't support pom.xml in a sub directory.

if you put parent pom.xml at the root folder, jitpack.io may found the java project.

thanks,

**Comment by lostromb** [comment]
I don't even know what a pom is. I just added one because I thought there needed to be one. PLEASE fix it for me and I will be happy to approve the PR!
