### ISSUE TITLE
OpusFile class in C#?

### ISSUE THREAD

**Issue by SylvainDebaudringhien** [lostromb/concentus#27]
Hi,
I wonder if Concentus can be used to decode a joint-stereo .opus file to PCM.

I see a reference to an OpusFile class in the Java console example.
Would this allow for joint stereo decoding, and could it be made C# compatible?

Thanks,
Sylvain.

**Comment by SylvainDebaudringhien** [comment]
Sorry, just seen that it was another repository... ;)

**Comment by tanzl18** [comment]
Hi!
I have the same problem as you did, "I see a reference to an OpusFile class in the Java console example.".
Can you give me the link of the repository?
Thanks a lot!
