### ISSUE TITLE
CELTMode for 48k sampling rate and 320 frame size

### ISSUE THREAD

**Issue by ydan87** [lostromb/concentus#28]
Hello there,
I have an embedded device that uses a C library of CELT encoder\decoder to encode 640-byte (320 shorts) audio data into 40 bytes and vice versa.
I'm now trying to use the CELT part of this library to do the same in C#.

However, it seems that while in the C library I can freely initialize the mode by just giving sampling rate, channels and frame size, this library is "locked" on a single CELTMode with frame size of 960.

Is there a possibility that a more general CELTMode initializer will be developed here or any other way that one can get the right CELTMode for that frame size?
Thanks in advance.

**Comment by lostromb** [comment]
I think that's just a side effect of how CELT was originally modified to suit the Opus spec. It's possible that you can work around it either using the ExpertFrameDuration parameter to force a particular frame size, or by porting over to C# the code that was used in the original C code to enable Opus "custom mode", which theoretically should allow for non-standard frame sizes. Are you trying to monotonously encode audio frames of 50ms each? You could encode 5 frames of 10ms each and bundle them together....

It sounds like you're hacking together something that rips the CELT functionality out of Opus and tries to use it independently; if so, why not just use FORCE_MODE_CELT and just let the Opus layer handle everything? If you're constrained by ROM size on your embedded device you could stub out all of the code on the SILK path to save some space. If you're trying to exactly conform to the original CELT spec, I don't know if that will be easy given how the code here was modified to suit Opus, and I don't know how much I can help you with it.

**Comment by ydan87** [comment]
Hi,
Using Opus in the device would be the best way to go for me. However we are very short in ROM and it seems that even before we force any mode, the library won't fit in memory.

**Comment by lostromb** [comment]
See the opus mailing list for some guidance on how to trim down ROM size, similar to your situation:
http://lists.xiph.org/pipermail/opus/2017-February/003764.html

**Comment by ydan87** [comment]
Hi,
Thanks for this important post. However that brings me back to the original issue of hard-coded 48000 sampling rate and 960 frame size mode. I need complexity in the C# side of Opus which I do not have.

Thanks anyway, I'm afraid I'll have to keep looking...
